version: 2

run:
  enable-cache: true
  timeout: 5m
  skip-dirs:
    - vendor
    - bundle
    - config
    - hack
    - helpers
    - img

linters-settings:
  staticcheck:
    checks: ["all", "-ST1005"]
  cyclop:
    max-complexity: 15
    package-average: 7.0

linters:
  disable-all: true
  enable:
    - goconst
    - gocritic
    - govet
    - unused
    - cyclop
    - staticcheck